Install Pandas Library

In [1]:
pip install pandas

Requirement already satisfied: pandas in C:\Users\ATIF\AppData\Local\Programs\Python\Python313\Lib\site-packages (2.3.2)
Requirement already satisfied: numpy>=1.26.0 in C:\Users\ATIF\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pandas) (2.3.3)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\ATIF\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in C:\Users\ATIF\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in C:\Users\ATIF\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in C:\Users\ATIF\AppData\Local\Programs\Python\Python313\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

Install Numpy Library

In [2]:
pip install numpy

Requirement already satisfied: numpy in C:\Users\ATIF\AppData\Local\Programs\Python\Python313\Lib\site-packages (2.3.3)
Note: you may need to restart the kernel to use updated packages.

Import Pandas Library

In [3]:
import pandas as pd

Import Numpy Library

In [4]:
import numpy as np

Creating Dataframe Python Dictionary

In [5]:
data_dict = {
    'Name': ['Ali', 'Ahmed', 'Sara', 'Zain', 'Ayesha'],
    'City': ['Karachi', 'Lahore', 'Islamabad', 'Multan', 'Peshawar'],
    'Salary': [55000, 62000, 75000, 48000, 51000]
}
df = pd.DataFrame(data_dict)
df

     Name       City  Salary
0     Ali    Karachi   55000
1   Ahmed     Lahore   62000
2    Sara  Islamabad   75000
3    Zain     Multan   48000
4  Ayesha   Peshawar   51000

Creating Dataframe Python List

In [6]:
data_list = [
    ['Ali', 'Karachi', 55000],
    ['Ahmed', 'Lahore', 62000],
    ['Sara', 'Islamabad', 75000],
    ['Zain', 'Multan', 48000],
    ['Ayesha', 'Peshawar', 51000]
]
df = pd.DataFrame(data_list)
df

        0          1      2
0     Ali    Karachi  55000
1   Ahmed     Lahore  62000
2    Sara  Islamabad  75000
3    Zain     Multan  48000
4  Ayesha   Peshawar  51000

In [7]:
data_list = [
    ['Ali', 'Karachi', 55000],
    ['Ahmed', 'Lahore', 62000],
    ['Sara', 'Islamabad', 75000],
    ['Zain', 'Multan', 48000],
    ['Ayesha', 'Peshawar', 51000]
]
df = pd.DataFrame(data_list)
# Columns ke naam sath de dein
df = pd.DataFrame(data_list,columns=['Name','City','Salary'])
df

     Name       City  Salary
0     Ali    Karachi   55000
1   Ahmed     Lahore   62000
2    Sara  Islamabad   75000
3    Zain     Multan   48000
4  Ayesha   Peshawar   51000

Single Column Select

In [8]:
# Jab aap df['Name'] likhte hain
# to Pandas poore table mein se sirf 'Name' wala column nikaal kar aapko dikhata hai.
df['Name']

0       Ali
1     Ahmed
2      Sara
3      Zain
4    Ayesha
Name: Name, dtype: object

Multiple Columns Select

In [9]:
# "Multiple Column Selection" kehlati hai. Jab aap double square brackets [[...]] 
# istemal karte hain, to Pandas aik naya DataFrame (chota table) nikaal kar deta hai
#jis mein sirf aap ke pasandida columns hote hain.
df[['Name','City']]

     Name       City
0     Ali    Karachi
1   Ahmed     Lahore
2    Sara  Islamabad
3    Zain     Multan
4  Ayesha   Peshawar

Creating a New Column

In [10]:
# df mein aik naya column 'Designation' shamil kar degi. Agar yeh column pehle se mojud hai,
# to yeh purani values ko in nayi values se badal (update) degi.
df['Designation'] = ['Junior Software Engineer','Software Engineer',
'Senior Software Engineer','Technical Lead','Software Architect']

In [11]:
df

     Name       City  Salary               Designation
0     Ali    Karachi   55000  Junior Software Engineer
1   Ahmed     Lahore   62000         Software Engineer
2    Sara  Islamabad   75000  Senior Software Engineer
3    Zain     Multan   48000            Technical Lead
4  Ayesha   Peshawar   51000        Software Architect

Single Column Removing

In [12]:
df.drop('Designation', axis = 1)

     Name       City  Salary
0     Ali    Karachi   55000
1   Ahmed     Lahore   62000
2    Sara  Islamabad   75000
3    Zain     Multan   48000
4  Ayesha   Peshawar   51000

In [13]:
df

     Name       City  Salary               Designation
0     Ali    Karachi   55000  Junior Software Engineer
1   Ahmed     Lahore   62000         Software Engineer
2    Sara  Islamabad   75000  Senior Software Engineer
3    Zain     Multan   48000            Technical Lead
4  Ayesha   Peshawar   51000        Software Architect

Single Column Permanently Removing

In [14]:
df.drop('Designation', axis = 1, inplace = True)

In [15]:
df

     Name       City  Salary
0     Ali    Karachi   55000
1   Ahmed     Lahore   62000
2    Sara  Islamabad   75000
3    Zain     Multan   48000
4  Ayesha   Peshawar   51000

Single Row Removing

In [16]:
df.drop(0, axis = 0)

     Name       City  Salary
1   Ahmed     Lahore   62000
2    Sara  Islamabad   75000
3    Zain     Multan   48000
4  Ayesha   Peshawar   51000

In [17]:
df

     Name       City  Salary
0     Ali    Karachi   55000
1   Ahmed     Lahore   62000
2    Sara  Islamabad   75000
3    Zain     Multan   48000
4  Ayesha   Peshawar   51000

Single Row Permanently Removing

In [18]:
df.drop(0, axis = 0, inplace = True)

In [19]:
df

     Name       City  Salary
1   Ahmed     Lahore   62000
2    Sara  Islamabad   75000
3    Zain     Multan   48000
4  Ayesha   Peshawar   51000

Single Row Select

In [20]:
df.loc[1]

Name       Ahmed
City      Lahore
Salary     62000
Name: 1, dtype: object

Multiple Rows Select

In [21]:
df.loc[[2,3]]

   Name       City  Salary
2  Sara  Islamabad   75000
3  Zain     Multan   48000

Select Subsets of Rows and Columns

In [22]:
df.loc[[3,4]][['Name','City']]

     Name      City
3    Zain    Multan
4  Ayesha  Peshawar

Conditional Selection

In [23]:
df

     Name       City  Salary
1   Ahmed     Lahore   62000
2    Sara  Islamabad   75000
3    Zain     Multan   48000
4  Ayesha   Peshawar   51000

'Salary' wale column ki har value ko check karta hai aur ek True/False ki list (Series) banata hai.
Agar Salary 62,000 hai -> True
Agar Salary 55,000 hai -> False

In [24]:
df[df["Salary"] > 60000]

    Name       City  Salary
1  Ahmed     Lahore   62000
2   Sara  Islamabad   75000

Do Conditions Ek Saath Agar aapko wo log chahiye jin ki Salary > 60,000 ho aur wo 'Islamabad' mein rehte hon

In [25]:
df[(df["Salary"] > 60000) & (df["City"] == 'Islamabad')]

   Name       City  Salary
2  Sara  Islamabad   75000