In [1]:
pip install pandas

Requirement already satisfied: pandas in C:\Users\ATIF\AppData\Local\Programs\Python\Python313\Lib\site-packages (2.3.2)
Requirement already satisfied: numpy>=1.26.0 in C:\Users\ATIF\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pandas) (2.3.3)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\ATIF\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in C:\Users\ATIF\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in C:\Users\ATIF\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in C:\Users\ATIF\AppData\Local\Programs\Python\Python313\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [2]:
pip install numpy

Requirement already satisfied: numpy in C:\Users\ATIF\AppData\Local\Programs\Python\Python313\Lib\site-packages (2.3.3)
Note: you may need to restart the kernel to use updated packages.

Pandas Library Import

In [ ]:
import pandas as pd

Numpy Library Import

In [ ]:
import numpy as np

In [ ]:
Creating a DataFrame

In [5]:
data = {
    'Name':['Ali','Ahmed','Sara','Zain','Ayesha'],
    'City':['Karachi','Lahore','Islamabad','Multan','Multan'],
    'Salary':[50000,60000,70000,55000,65000]
}
pd.DataFrame(data)

     Name       City  Salary
0     Ali    Karachi   50000
1   Ahmed     Lahore   60000
2    Sara  Islamabad   70000
3    Zain     Multan   55000
4  Ayesha     Multan   65000

In [6]:
data_list = [
    ['Ali','Ahmed','Sara','Zain','Ayesha'],
    ['Karachi','Lahore','Islamabad','Multan','Multan'],
    [50000,60000,70000,55000,65000]
]
df2 = pd.DataFrame(data_list)

In [7]:
df2

         0       1          2       3       4
0      Ali   Ahmed       Sara    Zain  Ayesha
1  Karachi  Lahore  Islamabad  Multan  Multan
2    50000   60000      70000   55000   65000

Selection and Indexing of Columns

In [8]:
data_list = [
    ['Ali', 'Karachi', 50000],
    ['Ahmed', 'Lahore',60000],
    ['Sara', 'Islamabad', 70000],
    ['Zain','Multan', 55000],
    ['Ayesha', 'Multan', 65000]
]
df2 = pd.DataFrame(data_list)
columns = ['Name','City','Salary']
df2 = pd.DataFrame(data_list,columns =columns)
df2

     Name       City  Salary
0     Ali    Karachi   50000
1   Ahmed     Lahore   60000
2    Sara  Islamabad   70000
3    Zain     Multan   55000
4  Ayesha     Multan   65000

In [9]:
df2['Name']

0       Ali
1     Ahmed
2      Sara
3      Zain
4    Ayesha
Name: Name, dtype: object

In [10]:
df2[['Name','City']]

     Name       City
0     Ali    Karachi
1   Ahmed     Lahore
2    Sara  Islamabad
3    Zain     Multan
4  Ayesha     Multan

Creating a new column

In [11]:
df2['Designation'] = ['Software Engineer','Frontend Developer','Backend Developer','Full Stack Developer','Software Architect']

In [12]:
df2

     Name       City  Salary           Designation
0     Ali    Karachi   50000     Software Engineer
1   Ahmed     Lahore   60000    Frontend Developer
2    Sara  Islamabad   70000     Backend Developer
3    Zain     Multan   55000  Full Stack Developer
4  Ayesha     Multan   65000    Software Architect