Install Pandas Library

In [1]:
pip install pandas

Requirement already satisfied: pandas in C:\Users\ATIF\AppData\Local\Programs\Python\Python313\Lib\site-packages (2.3.2)
Requirement already satisfied: numpy>=1.26.0 in C:\Users\ATIF\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pandas) (2.3.3)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\ATIF\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in C:\Users\ATIF\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in C:\Users\ATIF\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in C:\Users\ATIF\AppData\Local\Programs\Python\Python313\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

Install Numpy Library

In [2]:
pip install numpy

Requirement already satisfied: numpy in C:\Users\ATIF\AppData\Local\Programs\Python\Python313\Lib\site-packages (2.3.3)
Note: you may need to restart the kernel to use updated packages.

Import Pandas Library

In [3]:
import pandas as pd

Import Numpy Library

In [4]:
import numpy as np

Creating DataFrame Python Dictionary

In [5]:
data = {
    'Name': ['Ali', 'Ahmed', 'Sara', 'Zain', 'Ayesha'],
    'City': ['Karachi', 'Lahore', 'Islamabad', 'Multan', 'Peshawar'],
    'Salary': [55000, 62000, 75000, 48000, 51000]
}
df = pd.DataFrame(data)
df

     Name       City  Salary
0     Ali    Karachi   55000
1   Ahmed     Lahore   62000
2    Sara  Islamabad   75000
3    Zain     Multan   48000
4  Ayesha   Peshawar   51000

Creating DataFrame Python List

In [6]:
data_list = [
    ['Ali', 'Karachi', 55000],
    ['Ahmed', 'Lahore', 62000],
    ['Sara', 'Islamabad', 75000],
    ['Zain', 'Multan', 48000],
    ['Ayesha', 'Peshawar', 51000]
]
df2 = pd.DataFrame(data_list)
df2

        0          1      2
0     Ali    Karachi  55000
1   Ahmed     Lahore  62000
2    Sara  Islamabad  75000
3    Zain     Multan  48000
4  Ayesha   Peshawar  51000

In [7]:
data_list = [
    ['Ali', 'Karachi', 55000],
    ['Ahmed', 'Lahore', 62000],
    ['Sara', 'Islamabad', 75000],
    ['Zain', 'Multan', 48000],
    ['Ayesha', 'Peshawar', 51000]
]
df2 = pd.DataFrame(data_list)
df2 = pd.DataFrame(data_list,columns=['Name','City','Salary'])
df2

     Name       City  Salary
0     Ali    Karachi   55000
1   Ahmed     Lahore   62000
2    Sara  Islamabad   75000
3    Zain     Multan   48000
4  Ayesha   Peshawar   51000

In [8]:
df2['Name']

0       Ali
1     Ahmed
2      Sara
3      Zain
4    Ayesha
Name: Name, dtype: object

In [9]:
df[['Name','City']]

     Name       City
0     Ali    Karachi
1   Ahmed     Lahore
2    Sara  Islamabad
3    Zain     Multan
4  Ayesha   Peshawar

Creating a new column

In [ ]:
df2["Designation"] = ['Junior Developer','Backend Engineer', 'Senior Developer', 
'DevOps Engineer', 'Full Stack Developer']

In [12]:
df2

     Name       City  Salary           Designation
0     Ali    Karachi   55000      Junior Developer
1   Ahmed     Lahore   62000      Backend Engineer
2    Sara  Islamabad   75000      Senior Developer
3    Zain     Multan   48000       DevOps Engineer
4  Ayesha   Peshawar   51000  Full Stack Developer

Removing Columns

In [13]:
df2.drop('Designation',axis = 1)

     Name       City  Salary
0     Ali    Karachi   55000
1   Ahmed     Lahore   62000
2    Sara  Islamabad   75000
3    Zain     Multan   48000
4  Ayesha   Peshawar   51000

In [14]:
df2

     Name       City  Salary           Designation
0     Ali    Karachi   55000      Junior Developer
1   Ahmed     Lahore   62000      Backend Engineer
2    Sara  Islamabad   75000      Senior Developer
3    Zain     Multan   48000       DevOps Engineer
4  Ayesha   Peshawar   51000  Full Stack Developer

In [15]:
df2.drop('Designation',axis = 1, inplace=True)

In [16]:
df2

     Name       City  Salary
0     Ali    Karachi   55000
1   Ahmed     Lahore   62000
2    Sara  Islamabad   75000
3    Zain     Multan   48000
4  Ayesha   Peshawar   51000

In [17]:
df2.drop(['City','Salary'],axis = 1)

     Name
0     Ali
1   Ahmed
2    Sara
3    Zain
4  Ayesha

In [18]:
df2

     Name       City  Salary
0     Ali    Karachi   55000
1   Ahmed     Lahore   62000
2    Sara  Islamabad   75000
3    Zain     Multan   48000
4  Ayesha   Peshawar   51000

In [19]:
df2.drop(0,axis = 0)

     Name       City  Salary
1   Ahmed     Lahore   62000
2    Sara  Islamabad   75000
3    Zain     Multan   48000
4  Ayesha   Peshawar   51000

In [20]:
df2

     Name       City  Salary
0     Ali    Karachi   55000
1   Ahmed     Lahore   62000
2    Sara  Islamabad   75000
3    Zain     Multan   48000
4  Ayesha   Peshawar   51000

Selecting Rows

In [21]:
df2

     Name       City  Salary
0     Ali    Karachi   55000
1   Ahmed     Lahore   62000
2    Sara  Islamabad   75000
3    Zain     Multan   48000
4  Ayesha   Peshawar   51000

In [23]:
df2.loc[0]

Name          Ali
City      Karachi
Salary      55000
Name: 0, dtype: object

In [24]:
df2.loc[[0,1]]

    Name     City  Salary
0    Ali  Karachi   55000
1  Ahmed   Lahore   62000

Selecting Subsets of Rows and Columns

In [26]:
df.loc[[0,1]][['City','Salary']]

      City  Salary
0  Karachi   55000
1   Lahore   62000