Install Pandas Library

In [1]:
pip install pandas

Requirement already satisfied: pandas in C:\Users\ATIF\AppData\Local\Programs\Python\Python313\Lib\site-packages (2.3.2)
Requirement already satisfied: numpy>=1.26.0 in C:\Users\ATIF\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pandas) (2.3.3)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\ATIF\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in C:\Users\ATIF\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in C:\Users\ATIF\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in C:\Users\ATIF\AppData\Local\Programs\Python\Python313\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

Install Numpy Library

In [2]:
pip install numpy

Requirement already satisfied: numpy in C:\Users\ATIF\AppData\Local\Programs\Python\Python313\Lib\site-packages (2.3.3)
Note: you may need to restart the kernel to use updated packages.

Pandas Library Import

In [3]:
import pandas as pd

Numpy Library Import

In [4]:
import numpy as np

Creating DataFrame Python Dictionary

In [5]:
data = {
    'Name': ['Ali', 'Ahmed', 'Sara', 'Zain', 'Ayesha'],
    'City': ['Karachi', 'Lahore', 'Islamabad', 'Multan', 'Peshawar'],
    'Salary': [55000, 62000, 75000, 48000, 51000]
}
df = pd.DataFrame(data)

In [6]:
df

     Name       City  Salary
0     Ali    Karachi   55000
1   Ahmed     Lahore   62000
2    Sara  Islamabad   75000
3    Zain     Multan   48000
4  Ayesha   Peshawar   51000

Creating DataFrame Python List

In [7]:
data_list = [
    ['Ali', 'Karachi', 55000],
    ['Ahmed', 'Lahore', 62000],
    ['Sara', 'Islamabad', 75000],
    ['Zain', 'Multan', 48000],
    ['Ayesha', 'Peshawar', 51000]
]
df2 = pd.DataFrame(data_list)

In [8]:
df2

        0          1      2
0     Ali    Karachi  55000
1   Ahmed     Lahore  62000
2    Sara  Islamabad  75000
3    Zain     Multan  48000
4  Ayesha   Peshawar  51000

In [10]:
data_list = [
    ['Ali', 'Karachi', 55000],
    ['Ahmed', 'Lahore', 62000],
    ['Sara', 'Islamabad', 75000],
    ['Zain', 'Multan', 48000],
    ['Ayesha', 'Peshawar', 51000]
]
df2 = pd.DataFrame(data_list)
df2 = pd.DataFrame(data_list, columns=['Name', 'City', 'Salary'])
df2

     Name       City  Salary
0     Ali    Karachi   55000
1   Ahmed     Lahore   62000
2    Sara  Islamabad   75000
3    Zain     Multan   48000
4  Ayesha   Peshawar   51000

Selection and Indexing of Columns

In [13]:
df2['Name']

0       Ali
1     Ahmed
2      Sara
3      Zain
4    Ayesha
Name: Name, dtype: object

In [14]:
df2[['Name','City']]

     Name       City
0     Ali    Karachi
1   Ahmed     Lahore
2    Sara  Islamabad
3    Zain     Multan
4  Ayesha   Peshawar