In [1]:
pip install pandas

Requirement already satisfied: pandas in C:\Users\ATIF\AppData\Local\Programs\Python\Python313\Lib\site-packages (2.3.2)
Requirement already satisfied: numpy>=1.26.0 in C:\Users\ATIF\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pandas) (2.3.3)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\ATIF\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in C:\Users\ATIF\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in C:\Users\ATIF\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in C:\Users\ATIF\AppData\Local\Programs\Python\Python313\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.0.1 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
pip install numpy

Requirement already satisfied: numpy in C:\Users\ATIF\AppData\Local\Programs\Python\Python313\Lib\site-packages (2.3.3)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.0.1 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [3]:
import pandas as pd

In [4]:
import numpy as np

In [5]:
# File Read Karna
df = pd.read_csv("employees.csv")
df = pd.DataFrame(df)
df

      ID   Name        City   Salary   Designation
0      1    Ali   Islamabad  65000.0        DevOps
1      2   Iqra  Faisalabad  55000.0        DevOps
2      3   Sara   Islamabad  70000.0  Data Analyst
3      4   Sara     Karachi      NaN    Junior Dev
4      5   Taha      Quetta  50000.0   ML Engineer
..   ...    ...         ...      ...           ...
195  196   Taha      Quetta  50000.0   ML Engineer
196  197   Hina      Lahore  60000.0        DevOps
197  198   Zain   Islamabad  50000.0   ML Engineer
198  199  Bilal   Islamabad  60000.0    Junior Dev
199  200   Noor      Multan  45000.0    Senior Dev

[200 rows x 5 columns]

In [7]:
# First Rows Data Dekhna
df.head(60)

    ID    Name        City   Salary   Designation
0    1     Ali   Islamabad  65000.0        DevOps
1    2    Iqra  Faisalabad  55000.0        DevOps
2    3    Sara   Islamabad  70000.0  Data Analyst
3    4    Sara     Karachi      NaN    Junior Dev
4    5    Taha      Quetta  50000.0   ML Engineer
5    6     Ali   Islamabad  65000.0  Data Analyst
6    7    Hina      Lahore  60000.0        DevOps
7    8    Zain   Islamabad  50000.0   ML Engineer
8    9   Bilal   Islamabad  60000.0    Junior Dev
9   10    Noor      Multan  45000.0    Senior Dev
10  11     Ali   Islamabad  65000.0        DevOps
11  12    Iqra  Faisalabad  55000.0        DevOps
12  13    Sara   Islamabad  70000.0  Data Analyst
13  14    Sara     Karachi      NaN    Junior Dev
14  15    Taha      Quetta  50000.0   ML Engineer
15  16     Ali   Islamabad  65000.0  Data Analyst
16  17    Hina      Lahore  60000.0        DevOps
17  18    Zain   Islamabad  50000.0   ML Engineer
18  19   Bilal   Islamabad  60000.0    Junior Dev
19  20    Noor      Multan  45000.0    Senior Dev
20  21   Ahmed     Karachi      NaN  Data Analyst
21  22  Ayesha      Lahore  58000.0           NaN
22  23     Ali         NaN  65000.0        DevOps
23  24    Iqra  Faisalabad      NaN        DevOps
24  25    Sara   Islamabad  70000.0           NaN
25  26    Taha         NaN  50000.0   ML Engineer
26  27    Hina      Lahore      NaN        DevOps
27  28    Zain   Islamabad  50000.0           NaN
28  29   Bilal         NaN  60000.0    Junior Dev
29  30    Noor      Multan      NaN    Senior Dev
30  31   Ahmed     Karachi  52000.0  Data Analyst
31  32  Ayesha      Lahore  58000.0    Junior Dev
32  33     Ali   Islamabad  65000.0        DevOps
33  34    Iqra  Faisalabad  55000.0        DevOps
34  35    Sara   Islamabad  70000.0  Data Analyst
35  36    Taha      Quetta  50000.0   ML Engineer
36  37    Hina      Lahore  60000.0        DevOps
37  38    Zain   Islamabad  50000.0   ML Engineer
38  39   Bilal   Islamabad  60000.0    Junior Dev
39  40    Noor      Multan  45000.0    Senior Dev
40  41   Ahmed     Karachi  52000.0  Data Analyst
41  42  Ayesha      Lahore  58000.0    Junior Dev
42  43     Ali   Islamabad  65000.0        DevOps
43  44    Iqra  Faisalabad  55000.0        DevOps
44  45    Sara   Islamabad  70000.0  Data Analyst
45  46    Taha      Quetta  50000.0   ML Engineer
46  47    Hina      Lahore  60000.0        DevOps
47  48    Zain   Islamabad  50000.0   ML Engineer
48  49   Bilal   Islamabad  60000.0    Junior Dev
49  50    Noor      Multan  45000.0    Senior Dev
50  51   Ahmed     Karachi  52000.0  Data Analyst
51  52  Ayesha      Lahore  58000.0    Junior Dev
52  53     Ali   Islamabad  65000.0        DevOps
53  54    Iqra  Faisalabad  55000.0        DevOps
54  55    Sara   Islamabad  70000.0  Data Analyst
55  56    Taha      Quetta  50000.0   ML Engineer
56  57    Hina      Lahore  60000.0        DevOps
57  58    Zain   Islamabad  50000.0   ML Engineer
58  59   Bilal   Islamabad  60000.0    Junior Dev
59  60    Noor      Multan  45000.0    Senior Dev

In [8]:
# Last Rows Data Dekhna
df.tail(40)

      ID    Name        City   Salary   Designation
160  161   Ahmed     Karachi  52000.0  Data Analyst
161  162  Ayesha      Lahore  58000.0    Junior Dev
162  163     Ali   Islamabad  65000.0        DevOps
163  164    Iqra  Faisalabad  55000.0        DevOps
164  165    Sara   Islamabad  70000.0  Data Analyst
165  166    Taha      Quetta  50000.0   ML Engineer
166  167    Hina      Lahore  60000.0        DevOps
167  168    Zain   Islamabad  50000.0   ML Engineer
168  169   Bilal   Islamabad  60000.0    Junior Dev
169  170    Noor      Multan  45000.0    Senior Dev
170  171   Ahmed     Karachi  52000.0  Data Analyst
171  172  Ayesha      Lahore  58000.0    Junior Dev
172  173     Ali   Islamabad  65000.0        DevOps
173  174    Iqra  Faisalabad  55000.0        DevOps
174  175    Sara   Islamabad  70000.0  Data Analyst
175  176    Taha      Quetta  50000.0   ML Engineer
176  177    Hina      Lahore  60000.0        DevOps
177  178    Zain   Islamabad  50000.0   ML Engineer
178  179   Bilal   Islamabad  60000.0    Junior Dev
179  180    Noor      Multan  45000.0    Senior Dev
180  181   Ahmed     Karachi  52000.0  Data Analyst
181  182  Ayesha      Lahore  58000.0    Junior Dev
182  183     Ali   Islamabad  65000.0        DevOps
183  184    Iqra  Faisalabad  55000.0        DevOps
184  185    Sara   Islamabad  70000.0  Data Analyst
185  186    Taha      Quetta  50000.0   ML Engineer
186  187    Hina      Lahore  60000.0        DevOps
187  188    Zain   Islamabad  50000.0   ML Engineer
188  189   Bilal   Islamabad  60000.0    Junior Dev
189  190    Noor      Multan  45000.0    Senior Dev
190  191   Ahmed     Karachi  52000.0  Data Analyst
191  192  Ayesha      Lahore  58000.0    Junior Dev
192  193     Ali   Islamabad  65000.0        DevOps
193  194    Iqra  Faisalabad  55000.0        DevOps
194  195    Sara   Islamabad  70000.0  Data Analyst
195  196    Taha      Quetta  50000.0   ML Engineer
196  197    Hina      Lahore  60000.0        DevOps
197  198    Zain   Islamabad  50000.0   ML Engineer
198  199   Bilal   Islamabad  60000.0    Junior Dev
199  200    Noor      Multan  45000.0    Senior Dev

In [17]:
# Shape Rows & Columns Count Karte hai
df.shape

(200, 5)

In [18]:
# Column Names Dekhna
df.columns

Index(['ID', 'Name', 'City', 'Salary', 'Designation'], dtype='object')

In [19]:
# Data Types Dekhna
df.dtypes

ID               int64
Name            object
City            object
Salary         float64
Designation     object
dtype: object

In [20]:
# Information Dekhna
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   ID           200 non-null    int64
 1   Name         200 non-null    object
 2   City         197 non-null    object
 3   Salary       200 non-null    float64
 4   Designation  197 non-null    object
dtypes: float64(1), int64(1), object(3)
memory usage: 7.9+ KB

In [21]:
# Statistics Dekhna
df.describe()

               ID        Salary
count  200.000000    200.000000
mean   100.500000  56690.721649
std     57.879185   7206.726094
min      1.000000  45000.000000
25%     50.750000  50000.000000
50%    100.500000  56690.721649
75%    150.250000  60000.000000
max    200.000000  70000.000000

In [ ]:
# Check Null Values
df.isnull()
# Count Null Values Check karna
df.isnull().sum()

In [13]:
# Fill Missing Values
# df["Salary"] = df["Salary"].fillna(40000)
# Column Mean Se Fill
df["Salary"] = df["Salary"].fillna(df["Salary"].mean())

In [ ]:
# Remove missing Values rows
# df.dropna

In [16]:
# Missing Values Counts
df["Salary"].isnull().sum()

np.int64(0)

In [15]:
# Column Selection
# Single Column Dekhna
df["Salary"]

0      65000.000000
1      55000.000000
2      70000.000000
3      56690.721649
4      50000.000000
           ...
195    50000.000000
196    60000.000000
197    50000.000000
198    60000.000000
199    45000.000000
Name: Salary, Length: 200, dtype: float64

In [22]:
# Multiple Column Dekhna
df[["Name", "Salary"]]

      Name        Salary
0      Ali  65000.000000
1     Iqra  55000.000000
2     Sara  70000.000000
3     Sara  56690.721649
4     Taha  50000.000000
..     ...           ...
195   Taha  50000.000000
196   Hina  60000.000000
197   Zain  50000.000000
198  Bilal  60000.000000
199   Noor  45000.000000

[200 rows x 2 columns]

In [24]:
# Row Selection
# Single Row Dekhna
df.iloc[1]

ID                      2
Name                 Iqra
City           Faisalabad
Salary            55000.0
Designation        DevOps
Name: 1, dtype: object

In [27]:
# Multiple Rows Dekhna 
df.iloc[0:20]

    ID   Name        City        Salary   Designation
0    1    Ali   Islamabad  65000.000000        DevOps
1    2   Iqra  Faisalabad  55000.000000        DevOps
2    3   Sara   Islamabad  70000.000000  Data Analyst
3    4   Sara     Karachi  56690.721649    Junior Dev
4    5   Taha      Quetta  50000.000000   ML Engineer
5    6    Ali   Islamabad  65000.000000  Data Analyst
6    7   Hina      Lahore  60000.000000        DevOps
7    8   Zain   Islamabad  50000.000000   ML Engineer
8    9  Bilal   Islamabad  60000.000000    Junior Dev
9   10   Noor      Multan  45000.000000    Senior Dev
10  11    Ali   Islamabad  65000.000000        DevOps
11  12   Iqra  Faisalabad  55000.000000        DevOps
12  13   Sara   Islamabad  70000.000000  Data Analyst
13  14   Sara     Karachi  56690.721649    Junior Dev
14  15   Taha      Quetta  50000.000000   ML Engineer
15  16    Ali   Islamabad  65000.000000  Data Analyst
16  17   Hina      Lahore  60000.000000        DevOps
17  18   Zain   Islamabad  50000.000000   ML Engineer
18  19  Bilal   Islamabad  60000.000000    Junior Dev
19  20   Noor      Multan  45000.000000    Senior Dev

In [28]:
# Condition
df[df["Salary"] > 60000]

      ID  Name       City   Salary   Designation
0      1   Ali  Islamabad  65000.0        DevOps
2      3  Sara  Islamabad  70000.0  Data Analyst
5      6   Ali  Islamabad  65000.0  Data Analyst
10    11   Ali  Islamabad  65000.0        DevOps
12    13  Sara  Islamabad  70000.0  Data Analyst
15    16   Ali  Islamabad  65000.0  Data Analyst
22    23   Ali        NaN  65000.0        DevOps
24    25  Sara  Islamabad  70000.0           NaN
32    33   Ali  Islamabad  65000.0        DevOps
34    35  Sara  Islamabad  70000.0  Data Analyst
42    43   Ali  Islamabad  65000.0        DevOps
44    45  Sara  Islamabad  70000.0  Data Analyst
52    53   Ali  Islamabad  65000.0        DevOps
54    55  Sara  Islamabad  70000.0  Data Analyst
62    63   Ali  Islamabad  65000.0        DevOps
64    65  Sara  Islamabad  70000.0  Data Analyst
72    73   Ali  Islamabad  65000.0        DevOps
74    75  Sara  Islamabad  70000.0  Data Analyst
82    83   Ali  Islamabad  65000.0        DevOps
84    85  Sara  Islamabad  70000.0  Data Analyst
92    93   Ali  Islamabad  65000.0        DevOps
94    95  Sara  Islamabad  70000.0  Data Analyst
102  103   Ali  Islamabad  65000.0        DevOps
104  105  Sara  Islamabad  70000.0  Data Analyst
112  113   Ali  Islamabad  65000.0        DevOps
114  115  Sara  Islamabad  70000.0  Data Analyst
122  123   Ali  Islamabad  65000.0        DevOps
124  125  Sara  Islamabad  70000.0  Data Analyst
132  133   Ali  Islamabad  65000.0        DevOps
134  135  Sara  Islamabad  70000.0  Data Analyst
142  143   Ali  Islamabad  65000.0        DevOps
144  145  Sara  Islamabad  70000.0  Data Analyst
152  153   Ali  Islamabad  65000.0        DevOps
154  155  Sara  Islamabad  70000.0  Data Analyst
162  163   Ali  Islamabad  65000.0        DevOps
164  165  Sara  Islamabad  70000.0  Data Analyst
172  173   Ali  Islamabad  65000.0        DevOps
174  175  Sara  Islamabad  70000.0  Data Analyst
182  183   Ali  Islamabad  65000.0        DevOps
184  185  Sara  Islamabad  70000.0  Data Analyst
192  193   Ali  Islamabad  65000.0        DevOps
194  195  Sara  Islamabad  70000.0  Data Analyst