Install Pandas Library

In [1]:
pip install pandas

Requirement already satisfied: pandas in C:\Users\ATIF\AppData\Local\Programs\Python\Python313\Lib\site-packages (2.3.2)
Requirement already satisfied: numpy>=1.26.0 in C:\Users\ATIF\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pandas) (2.3.3)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\ATIF\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in C:\Users\ATIF\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in C:\Users\ATIF\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in C:\Users\ATIF\AppData\Local\Programs\Python\Python313\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

Install Numpy Library

In [2]:
pip install numpy

Requirement already satisfied: numpy in C:\Users\ATIF\AppData\Local\Programs\Python\Python313\Lib\site-packages (2.3.3)
Note: you may need to restart the kernel to use updated packages.

Import Pandas Library

In [3]:
import pandas as pd

Import Numpy Library

In [4]:
import numpy as np

Merging 2 DataFrames

In [5]:
# Dono Tables ko Jorna (Merging)
employees = pd.DataFrame({
    "employee_id": [101, 102, 103, 104, 105],
    "name": ["Ali Khan", "Sara Ahmed", "Bilal Raza", "Ayesha Noor", "Usman Tariq"],
    "department": ["HR", "IT", "Finance", "Marketing", "Sales"]
})
salaries = pd.DataFrame({
    "employee_id": [101, 102, 103, 104, 105],
    "salary": [50000, 60000, 55000, 65000, 70000],
    "bonus": [5000, 6000, 5500, 6500, 7000]
})

In [6]:
employees

   employee_id         name department
0          101     Ali Khan         HR
1          102   Sara Ahmed         IT
2          103   Bilal Raza    Finance
3          104  Ayesha Noor  Marketing
4          105  Usman Tariq      Sales

In [7]:
salaries

   employee_id  salary  bonus
0          101   50000   5000
1          102   60000   6000
2          103   55000   5500
3          104   65000   6500
4          105   70000   7000

In [8]:
pd.merge(employees,salaries)

   employee_id         name department  salary  bonus
0          101     Ali Khan         HR   50000   5000
1          102   Sara Ahmed         IT   60000   6000
2          103   Bilal Raza    Finance   55000   5500
3          104  Ayesha Noor  Marketing   65000   6500
4          105  Usman Tariq      Sales   70000   7000